### ISSUE TITLE
브레인스토밍 기획정리

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#10]
핵심 서비스 : AI 식단 추천으로 식단표 제공 서비스 / 그에 상응하는 식재료 리스트를 제공하고 사용자와 로컬 식자재 마트 사업자와의 플렛폼 역할 / 더 나아가면 식재료 도매업 -> 판매/배달 서비스 

벤치마킹 / 식단표 제공 서비스는 없음 / 로컬 식자재 사업체와 사용자간의 플렛폼 역할(다나와pc)(당근마켓)/ 식재료 도매업 판매,배달서비스 (마켓컬리 등) /
타겟 : 나주시내 식단 서비스를 원하는 사람 / 식자재 마트 사업체

타겟 선정 이유
나주시내 : 거래처 관리 때문(나주시내-> 광주-> 전남-> 전국)
식단 서비스 : 다이어트/건강/채식/가정식으로 나눠진다.

식단 추천 사용 데이터 : 나이/성별/키/몸무게/스마트워치(헬스 앱 데이터)
식단 데이터 : 메뉴(메뉴에 들어가는 식재료 list), 영양소 정보, 메뉴 조리법

**Comment by park121234** [comment]
수신양호~
